### ISSUE TITLE
Add sandbox resources like https://github.com/supabase-community/postgres-new/tree/main/apps/postgres-new

### ISSUE THREAD

**Issue by sersoage** [HKUSTDial/NL2SQL_Handbook#1]
Could you add your views on resources like https://github.com/supabase-community/postgres-new/tree/main/apps/postgres-new

**Comment by Apricity-lxy** [comment]
Thank you very much for your interest in our work!

postgres.new is an innovative platform that merges traditional database management with advanced large language models (currently GPT-4o in their project). It facilitates the automatic generation of ER diagrams and SQL, and offers intuitive data visualization through charts. This platform is especially useful for novices to quickly learn and implement database concepts, while also providing data analysts with an efficient tool for data processing. This project is a related application of NL2SQL.

If you have any other questions, feel free to discuss them with us!
